export {default as Footer} from "./footer/footer.component";
export {default as ControlPanel} from "./control-panel/control-panel.component";
export {default as Board} from "./Board/board.component";
export {default as Square} from "./Square/Square.component";
export {default as CreateBoard} from "./util/GameUtil";
export {default as Game} from "./game-panel/game-panel.component";
export {default as Taskbar} from "./taskbar/taskbar.component";
export {default as Menu} from "./Menu/menu.component";
export {default as GameOver} from "./GameOver/game-over";
